#!/bin/bash
if test "$1" == "" ;then
    echo $0 "<path>"
    exit
fi

d=`basename $1`
tar -zcf $d.tar.gz $d

cat > $d.bin <<"SCRIPT"
#!/bin/bash
echo ""
echo "Self Extracting Installer"
echo ""

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR
d=`ls`
echo ""
echo "Run the installer"
echo ""
cd $d
./.sfx.installer $*

cd $CDIR
rm -rf $TMPDIR

exit 0

__ARCHIVE_BELOW__
SCRIPT

cat $d.tar.gz >> $d.bin
chmod +x $d.bin
